@startuml
<style>
.weak {
    RoundCorner 15
}
.subtype {
    RoundCorner 15
}
</style>

skinparam nodesep 100
skinparam ranksep 100

object "&    " as Z {
    id
    --

}
object "A    " as A {
    a
    --
    b
}

object "miniA " as mA<<subtype>> {
    
    --
    m
}


object "B    " as B<<weak>> {
    
    --
    d

}

object "D    " as D {
    f
    g
    --

}

object "C    " as C<<weak>> {
    
    --
    e
}

object "E    " as E<<weak>> {
    
    --
    
}

object "F    " as F<<weak>> {
    
    --
    bruh
    
}

object "G    " as G<<weak>> {
    
    --
    zuh    
}

object "H    " as H{
    juh
    --
    guh    
}

A ||--o| B
B ||--o{ C
D ||--o{ C
A -- mA: < isA 
C ||--o{ E
E -- F: < isA 

Z ||--o{ G
Z ||--o{ H

F ||--o{ G
F ||--o{ H

@enduml